### PR TITLE
ENHANCED: added unwrap() method and PlUnwrap()

### PR DESCRIPTION
**Pull request by kamahen**
This gets around the problem reported here: https://swi-prolog.discourse.group/t/ann-swi-prolog-9-1-17/6890/10

### CODE REVIEW

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/ann-swi-prolog-9-1-17/6890/17

**Comment by JanWielemaker** [comment]
Can we add `#define C_ unwrap()` to maintain compatibility?    I really dislike incompatible changes ...

**Comment by kamahen** [comment]
I've added `#define C_ unwrap()`.
Please don't merge yet; I want to look at adding `Plx_get_name_arity()` as discussed in a private email. (I may do it as a separate PR or a separate commit)

**Comment by kamahen** [comment]
Ready for review and merge. (I'l deal with `Plx_get_name_arity_ex()` in a separate PR.

**Comment by kamahen** [comment]
See Issue #60 -- I'll change `SWI-cpp2.h` to include `SWI-cpp2.cpp` (with some macros to allow separate compilation). I'll add to this PR if it hasn't been merged; otherwise I'll  make  a new PR.

**Pull request merged**
