### PR TITLE
MODIFIED: Return type wrappers changed to `bool`, matching SWI-Prolog.h

### PR DESCRIPTION
**Pull request by kamahen**
This matches the changes in SWI-Prolog.h with commit a1e914f

### CODE REVIEW

**Comment by kamahen** [comment]
The changes were done semi-manually, so there's the possibility of a mistake.

**Comment by JanWielemaker** [comment]
Note that the price of this is that it gets harder to keep the version included in the stable series up to data as we cannot simply share it any longer.    For now I have not updated any of the packages except for allowing a couple of them to compile with `stdbool.h` (resolving conflicts).

On the other hand it is a pity to loose this work.   Fork the one in stable and accept it will be harder to update?    Or keep this as a branch and merge on 9.4/9.5?

**Comment by kamahen** [comment]
I could add a macro PLX_BOOL that's "int" for stable and "bool" for dev?

**Comment by JanWielemaker** [comment]
> I could add a macro PLX_BOOL that's "int" for stable and "bool" for dev?

That would be a good solution.

**Comment by kamahen** [comment]
OK, I'll `#define PLX_BOOL bool` in my PR and you can change it to `int` when you backport. 
This will take a bit of work.

BTW, I could do this with a typedef instead of a macro -- would that be better?

**Comment by JanWielemaker** [comment]
> BTW, I could do this with a typedef instead of a macro -- would that be better?

Probably a macro is more ugly but more robust ...

**Comment by kamahen** [comment]
I would also want to incorporate the `WUNUSED` markings as `[[nodiscard]]` in the C++ wrappers -- would these changes also need a macro?
Existing code that doesn't compile with the additional `WUNUSED` or `[[no discard]]` attributes would be incorrect, so an incompatible backport would be OK?

**Comment by JanWielemaker** [comment]
I don't understand.    The `WUNUSED` are there for a long time, although currently only supported if gcc is used.   I don't like to change the way `WUNUSED` is used, except for several `bool` functions to which it should be added.   I do care a lot about backward compatibility and supporting as old as reasonable compilers.

**Comment by kamahen** [comment]
I was planning to add or change `[[no discard]]` attributes in `SWI-cpp2.h` and `SWI-cpp2-plx.h`, to match `WUNUSED` in `SWI-Prolog.h`. Would these changes also need to be macro-ized for backporting to stable, or would they be considered as bug-fixes -- that is, it would be OK for new `[[no discard]]` to cause a user of `SWI-cpp2.h` to not compile, because that code was erroneous in not using the return value.

**Comment by JanWielemaker** [comment]
Ah, I think I understand now.  No, I think that is fine.  As would be adding `WUNUSED` to place where it is missing in SWI-Prolog.h.  That merely captures errors.

**Comment by kamahen** [comment]
I've added a macro (controlled by PLVERSION) and proof-read the changes, so I think they're ready. Probably I need to update some documentation; but that can wait for the next pass, which will add `[[no discard]]`s.

**Comment by JanWielemaker** [comment]
Thanks.  Merged after squash of the two commits.

**Comment by kamahen** [comment]
It occurs to me that this might present back-porting problems to stable because it might wrap new `PL_*()` functions that aren't in the stable release. I've seen mixed  results  with "inline" functions in C++ -- sometimes  they seem to act like macros and are only expanded if they're used (in which case, there shouldn't be a backport problem) but sometimes they seem to be at least checked, regardless of whether they're used or not.

**Comment by JanWielemaker** [comment]
> it might wrap new `PL_*()` functions that aren't in the stable release.

We'll see the next release cycle.   If so, we can make these conditional or backport the PL_* functions if that has little consequences.   E.g., PL_free_term_ref() is stable, but only half functional as the impact for the entire thing is too large in my opinion.

**Pull request closed without merging**
