### PR TITLE
PlTerm::integer(), PlTerm_integer() overloading

### PR DESCRIPTION
**Pull request by kamahen**

### CODE REVIEW

**Comment by kamahen** [comment]
This also contains the test cases for PL_cvt_i_bool() for swipl-devel [PR 1060](https://github.com/SWI-Prolog/swipl-devel/pull/1060)

**Comment by kamahen** [comment]
I think that this PR supersedes https://github.com/SWI-Prolog/packages-cpp/pull/22/ ... I'll look into this and close/modify the two PRs as appropriate.

**Comment by kamahen** [comment]
BTW, PlAtom::reset() is used in rocksdb (in rocks_close/1).

**Comment by JanWielemaker** [comment]
Apparently we have some merge conflict, possibly due to my renaming.    The rename was useful, but possibly not a good idea in the middle of a PR.    Is this PR otherwise ok?   If so, I'll try to resolve the conflict.

**Comment by kamahen** [comment]
I also did a rename (cpp4pli.{cpp,pl} to test_cpp.{cpp.pl}), which might have messed things up (I also did a git stash push/pop, which seems to have lost the fact that I did "git mv"s and changed that to "rm" / "add").
Don't worry if you make a mistake with the merge; I'll check it when you're done and make a patch PR if needed.

**Comment by kamahen** [comment]
Also, some of the changes in https://github.com/SWI-Prolog/swipl-devel/pull/1060 produce different exceptions from what I expected, so I'll definitely be making a clean-up PR.

**Pull request merged**
