### PR TITLE
DOC: more details about exception handling

### PR DESCRIPTION
**Pull request by kamahen**
Also, some small code changes that showed up while reviewing the documentation.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/changes-to-swi-cpp-h/5601/54

**Comment by JanWielemaker** [comment]
Thanks.  That should hopefully complete the round.   Fixed two LaTeX errors and removed the fixme.   This is fixed in the core.   Seems you have not updated the core?

In the section "Notes on exception", I do not understand _"However, the C++ interface does not currently do this."_.   It passes an error term with an unbound 2nd argument, no?   That does all that is necessary.

I am worrying a little about exceptions from a query.    This means PL_next_solution() returns FALSE, PlQuery::next_solution() raises an exception (fine).    We still need to call PL_cut_query() before returning (FALSE).   Is that handled correctly by ~PlQuery?    Note that this call to PL_cut_query() cannot fail because the exception unwinding already dealt with Prolog cleanup handlers.

**Comment by kamahen** [comment]
To answer the question about `PL_next_solution()` returning `FALSE` ... here's some test code:
```
PREDICATE(hello, 0)
{ PlQuery q("write", PlTermv(PlTerm_atom("hello world\n")));
  PlCheck(q.next_solution());
  return true;
}
```
If `q.next_solution()` returns `false`, then `PlCheck()` will throw `PlFail()`. This will unwind the stack and will call `q.~PlQuery()`, which will call `q.cut()`, which will call `PL_cut_query()` if `q.qid` is non-zero (which it should be because if it's zero, `p.verify()` should throw `PlFail()`.

**Comment by kamahen** [comment]
To answer the question about "Notes on exception", _"However, the C++ interface does not currently do this."_ ...  maybe I misunderstood what `PL_error()` does ... `PlDomainError` simply constructs a term with the 2nd argument uninstantiated; but if I had called `PL_domain_error`, it would have filled in some other stuff, such as context. If the exception is thrown, then the surrounding "catch" will call `PL_raise_exception()`; but does this do everything that calling `PL_error()` would have done?

**Comment by kamahen** [comment]
OK, so re-reading the code for PL_error() and PL_raise_exception(), I think I mis-read some things ... if PL_raise_exception() is passed an arbitrary term with an uninstantiated variable for the 2nd argument, will it do the Right Thing in terms of messages, backtrace, context, etc.?

**Comment by JanWielemaker** [comment]
> OK, so re-reading the code for PL_error() and PL_raise_exception(), I think I mis-read some things ... if PL_raise_exception() is passed an arbitrary term with an uninstantiated variable for the 2nd argument, will it do the Right Thing in terms of messages, backtrace, context, etc.?

Yes.    The filling is done in the core when the exception is handled.   This finds the _catcher_ (if any), and calls the hooks in library(prolog_stack) to add the context when appropriate.

**Comment by kamahen** [comment]
I'm preparing a PR that fixes the documentation for exceptions.
Any suggestions on how to test that it does the Right Thing?

**Comment by kamahen** [comment]
As to `PlTermv` with zero items ...
- is it OK to call `PL_new_term_refs(0)` ?
- what do I pass to `PL_open_query()` if the term vector is empty? (or, perhaps it doesn't matter because `PL_predicate()` will have been given a size of 0 and therefore `t0` will be ignored?)

Also, I think the existing code for PlQuery is slightly wrong ... shouldn't it specify the module_t as NULL and let that default to either the calling context or "user", rather than specifying "user"?

**Pull request closed without merging**
