### PR TITLE
Added missing PlCheck()s, removed unnecessary [[nodiscard]]s

### PR DESCRIPTION
**Pull request by kamahen**
@JanWielemaker - Please review the code for PlQuery::cut()

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Getting ever better :smile: 

> @JanWielemaker - Please review the code for PlQuery::cut()

This is a bit hard.   I'd be tempted to map all exceptions that occur in calling Prolog to C++ exceptions.  That would turn cut() and close() into void method and ensure next_solution() will throw in the case of a Prolog exception (and thus only return logical success/failure[/last]).    But then, I see this remark

> // Don't do: PlCheck(close()) because must not throw exception in destructor

This is dubious anyway.   Why can't we throw from a destructor?   If we can't, we might raise a fatal error if we get to the destructor and the query has not been closed?    A small good news is that if next_solution() raised an exception, cut() and close() cannot fail because the cleanup handlers have already done their job as part of the exception unwinding.

Note that ignoring Prolog exceptions is simply not allowed.    For foreign predicates we __must__ either call PL_clear_exception() or return from the foreign predicate with `false`.    If we want to "handle" the exception in C(++) we must wrap the region where the exception may happen in PlFrame and `rewind` the frame to undo partial bindings that may have happened before the exception.    I have seen only a couple of places where this needed to be used.

**Comment by kamahen** [comment]
This is the issue with throwing an exception in a C++ destructor (more than you probably want to know). I'm reinstating the "throw", although not referencing this commentary:
https://stackoverflow.com/questions/130117/if-you-shouldnt-throw-exceptions-in-a-destructor-how-do-you-handle-errors-in-i

I am putting together a PR that improves on the current code, but it probably won't cover every corner case.

As to `PlQuery::cut()` ... the original code (in SWI-cpp.h) simply had a call to `PL_cut_query()` in its destructor (and didn't check the return code, which I presume was an oversight). I split this out as a separate method, so that the C++ code could do its own "`!`". I agree with changing this into a void method, and will make the appropriate code changes.

There is one test case that tries to call a non-existent predicate; it ends up with an `existence_error`, but I think that is generated by `next_solution()` rather than but the `cut()` ... is it even possible for an error to show up in the "cut", I wonder? ...

**Comment by JanWielemaker** [comment]
> There is one test case that tries to call a non-existent predicate; it ends up with an `existence_error`, but I think that is generated by `next_solution()` rather than but the `cut()` ... is it even possible for an error to show up in the "cut", I wonder? ...

To trigger this path I think you need something like below.   Now call next_solution() once and then cut().  That should trigger the invalid atom_codes/2 and raise an exception.    Not sure whether the core handles all that correctly.   It is a rather uncommon thing to do :smile: 

```
test :- setup_call_cleanup(true, between(1, 5, X), atom_codes(_,_)).
```

**Comment by kamahen** [comment]
I'm a bit confused as to how this is used to test throwing an exception in `~PlQuery()`:
```
test :- setup_call_cleanup(true, between(1, 5, X), atom_codes(_,_)).
```
Do you mean that it should be called by something like the following:
```
PREDICATE(test_test,0)
{  PlQuery q("test");
    PlCheck(q.next_solutions());
    PlCheck(q.cut());
    return true;
}
```
BTW, when I run `test` this way, I get:
```
?- test.
true 

ERROR: Arguments are not sufficiently instantiated
ERROR: In:
ERROR:    [7] atom_codes(_18540,_18542)
ERROR:    [6] <meta call>
```

Incidentally ... we don't seem to have a way of calling a predicate with zero args (or creating PlTermv with 0 items). I'll have to fix that.

**Comment by JanWielemaker** [comment]
> Do you mean that it should be called by something like the following:

yes

> BTW, when I run `test` this way, I get:

That is what you expect.   test/0 succeeds and when the toplevel discards the choicepoint the invalid atom_codes/2 is executed.

> PlTermv with 0 items

Yes.   A term vector with 0 elements is required ...

**Pull request merged**
