### PR TITLE
Silence uninitialized variable warning from gcc-11

### PR DESCRIPTION
**Pull request by kamahen**

### CODE REVIEW

**Comment by JanWielemaker** [comment]
I'm not convinced.   First of all, the one I labeled is the only one that requires action; the others are silent.   Is this the compiler?   More fundamentally though, should compare be allowed to throw an exception?    Except for internal consistency errors I do not think there should be any error condition.    Surely, returning -1 is not a good idea.   Can this happen?

I think we only need to take action on this one example.   I'm just wondering what the action should be.   I'm happy with a dummy initialization if it is just the compiler that can't figure out that the initialization is not needed (with a comment that says the only purpose is to silence the compiler).

**Comment by kamahen** [comment]
Yes, -1 is a bad default value, although I think it's just a situation of the compiler not being able to figure out that the initialization isn't needed. The same value as the "catch" makes sense; except in the case of compare(), the rc always has a meaning (-1, 0, 1) and the check for `rc_try` is compiled away unless `NDEBUG`.
I can't prevent an exception in the user-defined `compare_fields()` and it could theoretically happen if a `PL_free_blob()` gets done on one of the objects (or if there's a bug in Prolog and the user has a `dynamic_cast` that detects the wrong class has been given to the comparison).

Looking at my changes in https://github.com/SWI-Prolog/packages-cpp/pull/75 , I think I prefer initialization for the `rc` for all the try/catch's - the code is easier to read that way - it's clear what the value is if there's an exception (the `catch` matches the initialization).

**Comment by JanWielemaker** [comment]
The rule I use is to not initialize variables if they need different initialization in different control paths.   Then the compiler will tell you you forgot one of the control paths.    Less and less often, the compiler gets it wrong, which is when I initialize with a dummy value and comment.    If we look for example at acquire() where you propose to initialize `rc` it is already initialized in both paths.

I think that exceptions in acquire, compare and probably some more should terminate the process.  They should not happen and we can't do anything sensible.   E.g., returning `true` from a failed acquire() is not a sensible path to continue execution.    Either we should implement exception handling at the Prolog side and propagate these, or we should define that exceptions there terminate the process.    I vote for the latter.    Only for write() and possible for save()/load() I think exceptions are ok.    The others are called from locations that make propagating them pretty hard.

I guess the correct way is no try-catch block and let the exception kill the process or catch and call PL_fatal_error(), which will print and  terminate the process.     I think I vote for the simpler first.

**Comment by kamahen** [comment]
I think I prefer PL_fatal_error() because it can give more context than a C++ "unhandled exception" error.

The calls to compare(), write(), etc. can occur outside a PREDICATE, so I think I need to catch the C++ exceptions. (Most of SWI-cpp2.h can assume that it's inside a PREDICATE and therefore inside a try/catch)

**Comment by JanWielemaker** [comment]
> I think I prefer PL_fatal_error() because it can give more context than a C++ "unhandled exception" error.

Ok with that.   Not sure what to say that is much more informative though.   You cannot throw an exception, that is about it ...

> can occur outside a PREDICATE

They always occur outside a normal predicate block, but as far as they support exceptions they do support they same exception interface (error return code type/value may be different).

**Comment by kamahen** [comment]
So, if I call PL_raise_exception() return an error rc (e.g., from the write() callback), Prolog handles that properly?

This means that only compare() and acquire() need a try-catch with PL_fatal_error(). [Would this generate a traceback or does Prolog just throw up its hands?]

**Comment by JanWielemaker** [comment]
> So, if I call PL_raise_exception() return an error rc (e.g., from the write() callback), Prolog handles that properly?

Not sure it handles it properly, but that should be the interface.     We had discussions about that and I think it was implemented.

> PL_fatal_error(). [Would this generate a traceback or does Prolog just throw up its hands?]

PL_fatal_error() just prints and exits.    We could consider making sysError() public as PL_system_error().    That tries to generate an error report including C and Prolog stacks.   Also looks like a bit of an overkill.   acquire() typically adds the symbol to the struct and might set some flag.  Compare compares some fields.   What can go wrong?    Pretty much only serious memory corruption can make these things go wrong (I think).

**Comment by kamahen** [comment]
Thank-you for reminding me of our conversations about blob callbacks.

It's highly unlikely that something would go wrong with the callbacks unless PL_free_blob() had been called (or something was corrupted). But I think a call to sysError() would be better than a terse C++ "unhandled exception" fatal error (also in some other places where there's just an assert() call).

I'll add some test cases to cpp_test.pl, to ensure that PL_blob_data() returning NULL is handled properly.

**Comment by JanWielemaker** [comment]
I'm not against exporting sysError() (as PL_system_error()).   Possibly we do want some indication that the error is raised by something external though.    sysError() was intended for internal Prolog errors.   I still think it is a bit overkill.   assert() has indeed the disadvantage that whether it takes effect depends on how the compiler is called, but C++ exceptions do kill the process with a message.

**Comment by kamahen** [comment]
I'm pausing this PR for now - my git repository is corrupted and I'm restoring things (a bit of a messy process)

**Comment by kamahen** [comment]
Replaced by https://github.com/SWI-Prolog/packages-cpp/pull/78

**Pull request closed without merging**
