### PR TITLE
MODIFIED: SWI-cpp2.h includes inlined methods by default

### PR DESCRIPTION
**Pull request by kamahen**
This might break code that has `#include <SWI-cpp2.cpp>` - if you wish a separate compilation, define macro `_SWI_CPP2_CPP_SEPARATE` before the  `#include <SWI-cpp2.h>`.

### CODE REVIEW

**Comment by kamahen** [comment]
Correction: I've tested this with some code that has  `#include <SWI-cpp2.cpp>` and it didn't break.

**Comment by kamahen** [comment]
It appears that this wasn't added to the latest release (9.1.19). 
Note that https://github.com/SWI-Prolog/packages-swipl-win/pull/24 depends on this PR (also the PRs for rocksdb).

**Comment by JanWielemaker** [comment]
Forgot :cry:     Testing, only applying to cpp gets me this in swipl-win (and zillions more of these)

```
/home/janw/src/swipl-devel/packages/cpp/SWI-cpp2.cpp:54:1: error: ‘_SWI_CPP2_CPP_inline’ does not name a type
   54 | _SWI_CPP2_CPP_inline
      | ^~~~~~~~~~~~~~~~~~~~
```

I haven't looked at the why, but it would be great if we can avoid breaking things.

**Comment by kamahen** [comment]
I *think* that's because I modified swipl-win to fit with the separate compilation version of SWI-cpp2.{h,cpp}, and https://github.com/SWI-Prolog/packages-swipl-win/pull/24 restores things to the previous way of doing things. That is, I think that these changes to SWI-cpp2.h prevent breakage/confusion, which I had introduced (see issue https://github.com/SWI-Prolog/packages-cpp/issues/62).

But I'm not 100% sure and I probably won't be able to verify this until Nov 25 or so.

**Comment by JanWielemaker** [comment]
> That is, I think that these changes to SWI-cpp2.h prevent breakage/confusion, which I had introduced (see issue #62).

I understand.    This should improve portability with older versions, but breaks with newer :cry:    Most people do not like to keep changing their code ...    If there is no pressure I think I'll leave things as is for now and when you have time we should look for a solution that can deal with all the various conventions.

**Comment by kamahen** [comment]
I think I've fixed the problem, at the cost of slightly polluting the namespace with the macro `_SWI_CPP2_CPP_inline`.
I've tested with the current version of `packages/swipl-win` and my PR for it. (Also with `rockdb`)

**Comment by JanWielemaker** [comment]
Thanks.   Works :)

**Pull request merged**
