### PR TITLE
ENHANCED: experimental PlTermScoped API

### PR DESCRIPTION
**Pull request by kamahen**
Also some documentation fixes, and uses the new PL_api_error() in a few places.

TBD: add PlAtomScoped

The new experimental API is *not* documented yet.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/confusion-with-c-interface-and-prolog-lists/6355/36

**Comment by kamahen** [comment]
I am adding some test cases -- please don't merge this code until I finish them.
Also, `PlTermScoped::swap()` isn't working -- I might remove it. (Move constructors are difficult and the solution might be C++-20.)

**Comment by kamahen** [comment]
I've added documentation and tests; this is ready for review.

**Comment by kamahen** [comment]
I've reviewed my code against Microsoft's tutorial on move constructors: https://learn.microsoft.com/en-us/cpp/cpp/move-constructors-and-move-assignment-operators-cpp (my original code used an example from StackOverflow for unique_ptr that I now think was being overly clever and was also incomplete).

The whole thing could still have some subtle bugs in it, so I really wish a C++ expert could review it.

The Microsoft example move constructor looks a bit strange; I don't understand why the fields are first initialized and then changed (perhaps so that it looks similar to the `operator=` code?). Instead of the example code, I think this will do:
```cpp
// Move constructor.
MemoryBlock(MemoryBlock&& other) noexcept
   : _data(other._data)     // Copy the data pointer and its length from the
   , _length(other._length) // source object.
{
   std::cout << "In MemoryBlock(MemoryBlock&&). length = "
             << other._length << ". Moving resource." << std::endl;
   // Release the data pointer from the source object so that
   // the destructor does not free the memory multiple times.
   other._data = nullptr;
   other._length = 0;
}
```

**Comment by kamahen** [comment]
This PR was not used - superseded by https://github.com/SWI-Prolog/packages-cpp/pull/85

**Pull request closed without merging**
